<?php

const DEFAULT_SHORT_LINK_ID_LENGTH = 8;
const DEFAULT_URL_MAX_LENGTH = 2048;
const DEFAULT_DATABASE_TABLE_NAME = 'linkcompactor';
const DEFAULT_SERVER_USE_HTTPS = false;
const DEFAULT_SERVER_PORT = 8568;
const DEFAULT_SERVER_DOMAIN = 'localhost';

define("SHORT_LINK_ID_LENGTH", getenv('SHORT_LINK_ID_LENGTH') ?: DEFAULT_SHORT_LINK_ID_LENGTH);
define("URL_MAX_LENGTH", getenv('URL_MAX_LENGTH') ?: DEFAULT_URL_MAX_LENGTH);
define("DATABASE_TABLE_NAME", getenv('DATABASE_TABLE_NAME') ?: DEFAULT_DATABASE_TABLE_NAME);
define("SERVER_USE_HTTPS", getenv('SERVER_USE_HTTPS') ?: DEFAULT_SERVER_USE_HTTPS);
define("SERVER_PORT", getenv('SERVER_PORT') ?: DEFAULT_SERVER_PORT);
define("SERVER_DOMAIN", getenv('SERVER_DOMAIN') ?: DEFAULT_SERVER_DOMAIN);