<?php

const DEFAULT_SHORT_LINK_ID_LENGTH = 8;
const DEFAULT_URL_MAX_LENGTH = 2048;
const DEFAULT_DATABASE_TABLE_NAME = 'linkcompactor';
const DEFAULT_SHORT_LINK_USE_HTTPS = false;
const DEFAULT_SHORT_LINK_PORT = 8568;
const DEFAULT_SHORT_LINK_DOMAIN = 'localhost';

define("SHORT_LINK_ID_LENGTH", getenv('SHORT_LINK_ID_LENGTH') ?: DEFAULT_SHORT_LINK_ID_LENGTH);
define("URL_MAX_LENGTH", getenv('URL_MAX_LENGTH') ?: DEFAULT_URL_MAX_LENGTH);
define("DATABASE_TABLE_NAME", getenv('DATABASE_TABLE_NAME') ?: DEFAULT_DATABASE_TABLE_NAME);
define("SHORT_LINK_USE_HTTPS", getenv('SHORT_LINK_USE_HTTPS') ?: DEFAULT_SHORT_LINK_USE_HTTPS);
define("SHORT_LINK_PORT", (int)getenv('SHORT_LINK_PORT') ?: DEFAULT_SHORT_LINK_PORT);
define("SHORT_LINK_DOMAIN", getenv('SHORT_LINK_DOMAIN') ?: DEFAULT_SHORT_LINK_DOMAIN);