services:
  linkcompactor:
    container_name: linkcompactor
    environment:
      DATABASE_TYPE: "mysql"
      MYSQL_DATABASE_HOST: "mysql:3306"
      MYSQL_DATABASE_NAME: "linkcompactor"
      MYSQL_DATABASE_USER: "root"
      MYSQL_DATABASE_PASSWORD: "root"
    restart: unless-stopped
    ports:
      - '8568:8080'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "linkcompactor"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
