services:
  linkshortener:
    container_name: linkshortener
    restart: unless-stopped
    volumes:
         - ./database:/var/www/html/database
    post_start:
      - command: chown -R www-data /var/www/html/database
        user: root
    ports:
      - '8568:8080'
