services:
  linkcompactor:
    image: serversideup/php:8.4-fpm-nginx
    container_name: linkcompactor
    restart: unless-stopped
    volumes:
         - ./:/var/www/html
    ports:
      - '8568:8080'
