<?php
// Change it to mysql to use a MySQL database
const DEFAULT_DATABASE_TYPE = 'sqlite';
const DEFAULT_SQLITE_DATABASE_PATH = __DIR__ . '/database/database.sqlite';
const DEFAULT_MYSQL_DATABASE_HOST = 'localhost:3306';
const DEFAULT_MYSQL_DATABASE_NAME = 'linkshortener';
const DEFAULT_MYSQL_DATABASE_USER = 'root';
const DEFAULT_MYSQL_DATABASE_PASSWORD = 'root';
const DEFAULT_MYSQL_DATABASE_CHARSET = 'utf8mb4';

define('DATABASE_TYPE', getenv('DATABASE_TYPE') ?: DEFAULT_DATABASE_TYPE);

define('SQLITE_DATABASE_PATH', "sqlite:" . (getenv('SQLITE_DATABASE_PATH') ?: DEFAULT_SQLITE_DATABASE_PATH));

define('MYSQL_DATABASE_HOST', getenv('MYSQL_DATABASE_HOST') ?: DEFAULT_MYSQL_DATABASE_HOST);
define('MYSQL_DATABASE_NAME', getenv('MYSQL_DATABASE_NAME') ?: DEFAULT_MYSQL_DATABASE_NAME);
define('MYSQL_DATABASE_USER', getenv('MYSQL_DATABASE_USER') ?: DEFAULT_MYSQL_DATABASE_USER);
define('MYSQL_DATABASE_PASSWORD', getenv('MYSQL_DATABASE_PASSWORD') ?: DEFAULT_MYSQL_DATABASE_PASSWORD);
define('MYSQL_DATABASE_CHARSET', getenv('MYSQL_DATABASE_CHARSET') ?: DEFAULT_MYSQL_DATABASE_CHARSET);
