<?php
// Change it to mysql to use a MySQL database, or to pgsql to use a PostgreSQL database
const DEFAULT_DATABASE_TYPE = 'sqlite';
const DEFAULT_SQLITE_DATABASE_PATH = __DIR__ . '/database/database.sqlite';
const DEFAULT_MYSQL_DATABASE_HOST = 'localhost';
const DEFAULT_MYSQL_DATABASE_PORT = '3306';
const DEFAULT_MYSQL_DATABASE_NAME = 'linkcompactor';
const DEFAULT_MYSQL_DATABASE_USER = 'root';
const DEFAULT_MYSQL_DATABASE_PASSWORD = 'root';
const DEFAULT_MYSQL_DATABASE_CHARSET = 'utf8mb4';

const DEFAULT_PGSQL_DATABASE_HOST = 'localhost';
const DEFAULT_PGSQL_DATABASE_PORT = '5432';
const DEFAULT_PGSQL_DATABASE_NAME = 'linkcompactor';
const DEFAULT_PGSQL_DATABASE_USER = 'postgres';
const DEFAULT_PGSQL_DATABASE_PASSWORD = 'postgres';

define('DATABASE_TYPE', getenv('DATABASE_TYPE') ?: DEFAULT_DATABASE_TYPE);

define('SQLITE_DATABASE_PATH', "sqlite:" . (getenv('SQLITE_DATABASE_PATH') ?: DEFAULT_SQLITE_DATABASE_PATH));

define('MYSQL_DATABASE_HOST', getenv('MYSQL_DATABASE_HOST') ?: DEFAULT_MYSQL_DATABASE_HOST);
define('MYSQL_DATABASE_PORT', getenv('MYSQL_DATABASE_PORT') ?: DEFAULT_MYSQL_DATABASE_PORT);
define('MYSQL_DATABASE_NAME', getenv('MYSQL_DATABASE_NAME') ?: DEFAULT_MYSQL_DATABASE_NAME);
define('MYSQL_DATABASE_USER', getenv('MYSQL_DATABASE_USER') ?: DEFAULT_MYSQL_DATABASE_USER);
define('MYSQL_DATABASE_PASSWORD', getenv('MYSQL_DATABASE_PASSWORD') ?: DEFAULT_MYSQL_DATABASE_PASSWORD);
define('MYSQL_DATABASE_CHARSET', getenv('MYSQL_DATABASE_CHARSET') ?: DEFAULT_MYSQL_DATABASE_CHARSET);

define('PGSQL_DATABASE_HOST', getenv('PGSQL_DATABASE_HOST') ?: DEFAULT_PGSQL_DATABASE_HOST);
define('PGSQL_DATABASE_PORT', getenv('PGSQL_DATABASE_PORT') ?: DEFAULT_PGSQL_DATABASE_PORT);
define('PGSQL_DATABASE_NAME', getenv('PGSQL_DATABASE_NAME') ?: DEFAULT_PGSQL_DATABASE_NAME);
define('PGSQL_DATABASE_USER', getenv('PGSQL_DATABASE_USER') ?: DEFAULT_PGSQL_DATABASE_USER);
define('PGSQL_DATABASE_PASSWORD', getenv('PGSQL_DATABASE_PASSWORD') ?: DEFAULT_PGSQL_DATABASE_PASSWORD);